services:
  database:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: whoareyou
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    networks:
      - back-tier

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: whoareyou
    ports:
      - "27017:27017"
    networks:
      - back-tier
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: wurstmeister/zookeeper:3.8.0
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  backend:
    build: ./backend
    image: backend
    depends_on:
      - database
      - mongodb
      - kafka
    ports:
      - "4040:4040"
    networks:
      - back-tier

networks:
  back-tier: {}

volumes:
  mongo_data:

