services:
  database:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: whoareyou
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3307"
    networks:
      - back-tier

  backend:
    image: taegun1011/whoareyou_backend
    depends_on:
      - database
    ports:
      - "4040:4040"
    networks:
    - back-tier

networks:
  back-tier: {}
