spring:
  application:
    name: whoareyou

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/who_are_you?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: developer
    password: P!ssw0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: mwJkCwJrXmz_coCMECD_
            client-secret: UQjKMXiTt6
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email, name, nickname, gender
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 4040

secret-key: ThisStatementIsJwtSecretKeyDoNotUseThisStatement

livekit:
  api:
    key: APIXAD86V8PHHZ2
    secret: Bi1l6R02usl4OirnJ1LMfPHaZuaGeaT8aAp41WzLXyf
  server:
    url: wss://myapp-yqvsqxqi.livekit.cloud


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

