-- insert into user (id, total_matching_count, email, gender, name, nickname, type)
-- values
-- (1, 0, "email1", "male", "name1", "nickname1", "general"),
-- (2, 0, "email2", "female", "name2", "nickname2", "general"),
-- (3, 0, "email3", "male", "name3", "nickname3", "general"),
-- (4, 0, "email4", "female", "name4", "nickname4", "general"),
-- (5, 0, "email5", "male", "name5", "nickname5", "general"),
-- (6, 0, "email6", "female", "name6", "nickname6", "general"),
-- (7, 0, "email7", "male", "name7", "nickname7", "general"),
-- (8, 0, "email8", "female", "name8", "nickname8", "general"),
-- (9, 0, "email9", "male", "name9", "nickname9", "general"),
-- (10, 0, "email10", "female", "name10", "nickname10", "general"),
-- (11, 0, "email9", "male", "name9", "황태건", "general"),
-- (12, 0, "email10", "female", "name10", "조성욱", "general");